config/routes.rb
SearchTheWritings::Application.routes.draw do
  resources :volumes

end

app/models/volume.rb
class Volume < ActiveRecord::Base
  attr_accessible :author, :body, :title
  
  validates :title, :presence => true
  
  searchable do
    text :title, :author, :body
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  # GET /volumes
  # GET /volumes.json
  def index
    @volumes = Volume.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @volumes }
    end
  end

  # GET /volumes/1
  # GET /volumes/1.json
  def show
    @volume = Volume.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @volume }
    end
  end

  # GET /volumes/new
  # GET /volumes/new.json
  def new
    @volume = Volume.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @volume }
    end
  end

  # GET /volumes/1/edit
  def edit
    @volume = Volume.find(params[:id])
  end

  # POST /volumes
  # POST /volumes.json
  def create
    @volume = Volume.new(params[:volume])

    respond_to do |format|
      if @volume.save
        format.html { redirect_to @volume, notice: 'Volume was successfully created.' }
        format.json { render json: @volume, status: :created, location: @volume }
      else
        format.html { render action: "new" }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /volumes/1
  # PUT /volumes/1.json
  def update
    @volume = Volume.find(params[:id])

    respond_to do |format|
      if @volume.update_attributes(params[:volume])
        format.html { redirect_to @volume, notice: 'Volume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volumes/1
  # DELETE /volumes/1.json
  def destroy
    @volume = Volume.find(params[:id])
    @volume.destroy

    respond_to do |format|
      format.html { redirect_to volumes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchTheWritings</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/volumes/_form.html.erb
<%= form_for(@volume) do |f| %>
  <% if @volume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volume.errors.count, "error") %> prohibited this volume from being saved:</h2>

      <ul>
      <% @volume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/volumes/edit.html.erb
<h1>Editing volume</h1>

<%= render 'form' %>

<%= link_to 'Show', @volume %> |
<%= link_to 'Back', volumes_path %>

app/views/volumes/index.html.erb
<h1>Listing volumes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @volumes.each do |volume| %>
  <tr>
    <td><%= volume.title %></td>
    <td><%= volume.author %></td>
    <td><%= volume.body %></td>
    <td><%= link_to 'Show', volume %></td>
    <td><%= link_to 'Edit', edit_volume_path(volume) %></td>
    <td><%= link_to 'Destroy', volume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Volume', new_volume_path %>

app/views/volumes/new.html.erb
<h1>New volume</h1>

<%= render 'form' %>

<%= link_to 'Back', volumes_path %>

app/views/volumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @volume.title %>
</p>

<p>
  <b>Author:</b>
  <%= @volume.author %>
</p>

<p>
  <b>Body:</b>
  <%= @volume.body %>
</p>


<%= link_to 'Edit', edit_volume_path(@volume) %> |
<%= link_to 'Back', volumes_path %>